import React from 'react';
import { Calendar, CheckCircle2, Flag } from 'lucide-react';

/**
 * MilestoneTimeline Component (FR-06, Section 5.1 ui_ux_plan.md)
 * Renders chronological roadmap checkpoints generated by Gemini AI.
 */
export default function MilestoneTimeline({ milestones = [], currency = 'INR' }) {
  if (!milestones || milestones.length === 0) {
    return null;
  }

  const formatCurrency = (val) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency,
      maximumFractionDigits: 0,
    }).format(val || 0);
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-IN', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  };

  return (
    <div className="relative pl-6 space-y-6 before:absolute before:left-[11px] before:top-2 before:bottom-2 before:w-0.5 before:bg-coffee-200">
      {milestones.map((m, index) => {
        const isLast = index === milestones.length - 1;
        return (
          <div key={index} className="relative group">
            {/* Timeline Node Dot */}
            <div
              className={`absolute -left-6 top-1 w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold transition shadow-sm ${
                isLast
                  ? 'bg-coffee-500 text-white ring-4 ring-coffee-100'
                  : 'bg-white border-2 border-coffee-400 text-coffee-700'
              }`}
            >
              {isLast ? <Flag className="w-3 h-3" /> : index + 1}
            </div>

            {/* Milestone Card */}
            <div className="bg-coffee-50/60 hover:bg-coffee-50 border border-coffee-200/70 rounded-2xl p-4 transition space-y-2">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                <h4 className="text-xs font-bold text-coffee-950 flex items-center gap-1.5">
                  <span>{m.milestoneName}</span>
                </h4>
                <div className="flex items-center gap-2 text-[11px] text-coffee-600 font-medium">
                  <span className="flex items-center gap-1">
                    <Calendar className="w-3 h-3 text-coffee-500" />
                    <span>Target: {formatDate(m.targetDate)}</span>
                  </span>
                  <span className="font-bold text-coffee-900 bg-white px-2 py-0.5 rounded-lg border border-coffee-200">
                    {formatCurrency(m.targetAmount)}
                  </span>
                </div>
              </div>

              {m.actionTip && (
                <p className="text-xs text-coffee-700 leading-relaxed font-normal bg-white/70 rounded-xl p-2.5 border border-coffee-100">
                  <span className="font-semibold text-coffee-900">Action Tip: </span>
                  {m.actionTip}
                </p>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}
